language: java
dist: trusty
cache:
  directories:
  - $HOME/.m2
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
#  - oraclejdk-ea
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk-ea